const HISTOPATHOLOGY = "Histopathology";
const CYTOLOGY = "Cytology";
const PAP = "Papanicolaou";
const CASES = "CASES";
const ABOUT = "ABOUT";
const SEE = "see";
const EDIT = "edit";
const CREATE = "create";
const DELETE = "delete";
const HOME = "https://syspdfsur.vercel.app/";
export { HISTOPATHOLOGY, CYTOLOGY, PAP, CASES, ABOUT, SEE, EDIT, CREATE, DELETE, HOME };
