import React, { useContext, useEffect, useState } from "react";
import {
  BookOpen,
  Mail,
  Github,
  Twitter,
  Linkedin,
  Menu,
  X,
  ArrowLeft,
  ArrowRight,
} from "lucide-react";
import { Case, CaseSlide } from "~/interfaces/Case.interface";
import ClientContext from "~/pages/blog_client/context/ClientContext";
import { useParams } from "react-router";
import { useNavigate } from "react-router-dom";
import Header from "~/pages/blog_client/sections/Header";

const blogImages = [
  {
    id: 1,
    src: "/placeholder.svg?height=400&width=600",
    alt: "AI-generated art piece 1",
    description:
      "An abstract representation of artificial intelligence, featuring interconnected nodes and vibrant colors.",
  },
  {
    id: 2,
    src: "/placeholder.svg?height=400&width=600",
    alt: "AI-generated art piece 2",
    description:
      "A surreal landscape created by AI, blending natural elements with futuristic structures.",
  },
  {
    id: 3,
    src: "/placeholder.svg?height=400&width=600",
    alt: "AI-generated art piece 3",
    description:
      "A portrait that showcases the blend of human features with machine-like precision and patterns.",
  },
  {
    id: 4,
    src: "/placeholder.svg?height=400&width=600",
    alt: "AI-generated art piece 4",
    description:
      "An AI's interpretation of a cityscape, featuring impossible architecture and dream-like elements.",
  },
  {
    id: 5,
    src: "/placeholder.svg?height=400&width=600",
    alt: "AI-generated art piece 5",
    description:
      "A cosmic scene generated by AI, exploring the depths of space with imaginative celestial bodies.",
  },
];

function CasePost() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [selected, setSelected] = useState<Case>({} as Case);
  const [slidesCases, setSlidesCases] = useState<CaseSlide[]>([] as CaseSlide[]);
  const [selectedImage, setSelectedImage] = useState(
    slidesCases[0] || {
      image_url: "/placeholder.svg?height=400&width=600",
      id: "default",
      description: "No hay Descripcion",
    },
  );
  const { cases, slides, setLoading, loading } = useContext(ClientContext);
  const { id } = useParams();
  const navigate = useNavigate();

  const selectCurrentCase = () => {
    setLoading(true);
    const currentCase = cases.data.find((currentCase) => currentCase.id === id);
    if (currentCase) {
      setSelected(currentCase);
    } else {
      navigate("/*");
    }
    setLoading(false);
  };

  useEffect(() => {
    selectCurrentCase();
  }, []);

  useEffect(() => {
    setLoading(true);
    if (selected.id) {
      const currentSlides = slides.data.filter((slide) => slide.case_id === selected.id);
      if (currentSlides.length > 0) {
        setSlidesCases(currentSlides);
        setSelectedImage(currentSlides[0]); // Establece el primer slide como el seleccionado por defecto
      }
    }
    setLoading(false);
  }, [selected, slides]);

  return (
    <div className="flex min-h-screen flex-col bg-purple-950 text-white">
      <Header />
      <main className="flex-1 pt-16">
        {loading && <h1>CARGANDO ...</h1>}
        {!loading && slidesCases && slides && (
          <article className="container mx-auto px-4 py-8">
            <h1 className="mb-4 text-3xl font-bold tracking-tighter text-yellow-400 sm:text-4xl md:text-5xl lg:text-6xl">
              {selected.title}
            </h1>
            <div className="prose prose-invert mt-8 max-w-none">
              <p>{selected.description}</p>
            </div>
            <div className="flex flex-col gap-8 md:flex-row">
              <div className="md:w-3/4">
                <div className="overflow-hidden rounded-lg bg-purple-900 shadow-lg">
                  <img
                    src={selectedImage?.image_url || ""}
                    alt={selectedImage?.id || ""}
                    className="h-auto w-full object-cover"
                  />
                  <div className="p-6">
                    <p className="text-lg text-gray-300">
                      {selectedImage?.description || "No hay Descripcion"}
                    </p>
                  </div>
                </div>
              </div>
              <div className="md:w-1/4">
                <h2 className="mb-4 text-xl font-bold text-yellow-400">Image Gallery</h2>
                <ul className="space-y-2">
                  {slidesCases.map((image) => (
                    <li key={image.id}>
                      <button
                        onClick={() => setSelectedImage(image)}
                        className={`w-full rounded-md p-2 text-left transition-colors ${
                          selectedImage?.id === image?.id
                            ? "bg-yellow-400 text-purple-950"
                            : "bg-purple-800 text-white hover:bg-purple-700"
                        }`}
                      >
                        {image?.title}
                      </button>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </article>
        )}
      </main>
      <footer className="w-full border-t border-purple-800 bg-purple-950 py-6">
        <div className="container mx-auto px-4 md:px-6">
          <div className="flex flex-col items-center justify-between gap-4 md:flex-row">
            <div className="flex space-x-4">
              <a href="#" className="text-gray-300 transition-colors hover:text-yellow-400">
                <Twitter className="h-5 w-5" />
              </a>
              <a href="#" className="text-gray-300 transition-colors hover:text-yellow-400">
                <Github className="h-5 w-5" />
              </a>
              <a href="#" className="text-gray-300 transition-colors hover:text-yellow-400">
                <Linkedin className="h-5 w-5" />
              </a>
            </div>
            <p className="text-center text-xs text-gray-400">
              © 2024 Raikonif. All rights reserved.
            </p>
          </div>
        </div>
      </footer>
      <div className="fixed bottom-4 left-4 right-4 flex justify-between">
        <button className="rounded-md bg-purple-900 px-4 py-2 text-yellow-400 transition-colors hover:bg-purple-800">
          <ArrowLeft className="mr-2 inline h-4 w-4" /> Previous Post
        </button>
        <button className="rounded-md bg-purple-900 px-4 py-2 text-yellow-400 transition-colors hover:bg-purple-800">
          Next Post <ArrowRight className="ml-2 inline h-4 w-4" />
        </button>
      </div>
    </div>
  );
}

export default CasePost;
