import React, { useState } from "react";
import {
  BookOpen,
  Mail,
  Github,
  Twitter,
  Linkedin,
  Menu,
  X,
  ArrowLeft,
  ArrowRight,
} from "lucide-react";

const blogImages = [
  {
    id: 1,
    src: "/placeholder.svg?height=400&width=600",
    alt: "AI-generated art piece 1",
    description:
      "An abstract representation of artificial intelligence, featuring interconnected nodes and vibrant colors.",
  },
  {
    id: 2,
    src: "/placeholder.svg?height=400&width=600",
    alt: "AI-generated art piece 2",
    description:
      "A surreal landscape created by AI, blending natural elements with futuristic structures.",
  },
  {
    id: 3,
    src: "/placeholder.svg?height=400&width=600",
    alt: "AI-generated art piece 3",
    description:
      "A portrait that showcases the blend of human features with machine-like precision and patterns.",
  },
  {
    id: 4,
    src: "/placeholder.svg?height=400&width=600",
    alt: "AI-generated art piece 4",
    description:
      "An AI's interpretation of a cityscape, featuring impossible architecture and dream-like elements.",
  },
  {
    id: 5,
    src: "/placeholder.svg?height=400&width=600",
    alt: "AI-generated art piece 5",
    description:
      "A cosmic scene generated by AI, exploring the depths of space with imaginative celestial bodies.",
  },
];

function CasePost() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [selectedImage, setSelectedImage] = useState(blogImages[0]);

  return (
    <div className="flex min-h-screen flex-col bg-purple-950 text-white">
      <header className="fixed z-50 flex h-16 w-full items-center bg-purple-950/80 px-4 backdrop-blur-md lg:px-6">
        <a className="flex items-center justify-center" href="#">
          <BookOpen className="h-6 w-6 text-yellow-400" />
          <span className="ml-2 text-xl font-bold text-white">Jane Doe</span>
        </a>
        <nav
          className={`ml-auto flex gap-4 sm:gap-6 ${
            isMenuOpen ? "flex" : "hidden"
          } absolute left-0 right-0 top-16 flex-col bg-purple-950 p-4 md:relative md:top-0 md:flex md:flex-row md:bg-transparent md:p-0`}
        >
          <a
            className="text-sm font-medium text-gray-300 transition-colors hover:text-yellow-400"
            href="#"
          >
            Home
          </a>
          <a
            className="text-sm font-medium text-gray-300 transition-colors hover:text-yellow-400"
            href="#"
          >
            Blog
          </a>
          <a
            className="text-sm font-medium text-gray-300 transition-colors hover:text-yellow-400"
            href="#"
          >
            About
          </a>
          <a
            className="text-sm font-medium text-gray-300 transition-colors hover:text-yellow-400"
            href="#"
          >
            Contact
          </a>
        </nav>
        <button
          className="ml-auto rounded-md p-2 text-white focus:outline-none focus:ring-2 focus:ring-yellow-400 md:hidden"
          onClick={() => setIsMenuOpen(!isMenuOpen)}
        >
          {isMenuOpen ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}
        </button>
      </header>
      <main className="flex-1 pt-16">
        <article className="container mx-auto px-4 py-8">
          <h1 className="mb-4 text-3xl font-bold tracking-tighter text-yellow-400 sm:text-4xl md:text-5xl lg:text-6xl">
            The Art of AI: A Visual Journey
          </h1>
          <div className="flex flex-col gap-8 md:flex-row">
            <div className="md:w-3/4">
              <div className="overflow-hidden rounded-lg bg-purple-900 shadow-lg">
                <img
                  src={selectedImage.src}
                  alt={selectedImage.alt}
                  className="h-auto w-full object-cover"
                />
                <div className="p-6">
                  <p className="text-lg text-gray-300">{selectedImage.description}</p>
                </div>
              </div>
              <div className="prose prose-invert mt-8 max-w-none">
                <p>
                  Artificial Intelligence has revolutionized many fields, and art is no exception.
                  This collection showcases the incredible potential of AI in creating visually
                  stunning and thought-provoking pieces that challenge our perception of creativity
                  and machine capabilities.
                </p>
                <p>
                  Each image in this series was generated using state-of-the-art AI algorithms,
                  trained on vast datasets of human-created art. The results are a fascinating blend
                  of familiar artistic styles and completely novel visual concepts that push the
                  boundaries of what we consider possible in art creation.
                </p>
                <p>
                  As you explore these images, consider the implications of AI in the art world. How
                  does this technology change our understanding of creativity? What role will human
                  artists play in a future where AI can generate stunning visuals in seconds? These
                  are just some of the questions we must grapple with as we stand at the
                  intersection of technology and art.
                </p>
              </div>
            </div>
            <div className="md:w-1/4">
              <h2 className="mb-4 text-xl font-bold text-yellow-400">Image Gallery</h2>
              <ul className="space-y-2">
                {blogImages.map((image) => (
                  <li key={image.id}>
                    <button
                      onClick={() => setSelectedImage(image)}
                      className={`w-full rounded-md p-2 text-left transition-colors ${
                        selectedImage.id === image.id
                          ? "bg-yellow-400 text-purple-950"
                          : "bg-purple-800 text-white hover:bg-purple-700"
                      }`}
                    >
                      {image.alt}
                    </button>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </article>
      </main>
      <footer className="w-full border-t border-purple-800 bg-purple-950 py-6">
        <div className="container mx-auto px-4 md:px-6">
          <div className="flex flex-col items-center justify-between gap-4 md:flex-row">
            <div className="flex space-x-4">
              <a href="#" className="text-gray-300 transition-colors hover:text-yellow-400">
                <Twitter className="h-5 w-5" />
              </a>
              <a href="#" className="text-gray-300 transition-colors hover:text-yellow-400">
                <Github className="h-5 w-5" />
              </a>
              <a href="#" className="text-gray-300 transition-colors hover:text-yellow-400">
                <Linkedin className="h-5 w-5" />
              </a>
            </div>
            <p className="text-xs text-gray-400">© 2023 Jane Doe. All rights reserved.</p>
            <nav className="flex gap-4 sm:gap-6">
              <a
                className="text-xs text-gray-400 underline-offset-4 hover:text-gray-200 hover:underline"
                href="#"
              >
                Terms of Service
              </a>
              <a
                className="text-xs text-gray-400 underline-offset-4 hover:text-gray-200 hover:underline"
                href="#"
              >
                Privacy
              </a>
            </nav>
          </div>
        </div>
      </footer>
      <div className="fixed bottom-4 left-4 right-4 flex justify-between">
        <button className="rounded-md bg-purple-900 px-4 py-2 text-yellow-400 transition-colors hover:bg-purple-800">
          <ArrowLeft className="mr-2 inline h-4 w-4" /> Previous Post
        </button>
        <button className="rounded-md bg-purple-900 px-4 py-2 text-yellow-400 transition-colors hover:bg-purple-800">
          Next Post <ArrowRight className="ml-2 inline h-4 w-4" />
        </button>
      </div>
    </div>
  );
}

export default CasePost;
